using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cecs475.Pokemon.Model {
	/*
	 * If we wanted to add behaviors to the classes generated by EF, we could do so here, as part of the
	 * partial class definition. For example, we could add the AttackTarget method from before.
	 */
	public partial class Pokemon {

	}
}
